[package]
name = "recaptcha"
description = "recaptcha response verification"
version = "0.6.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]
license = "MIT"
keywords = ["recaptcha", "captcha"]
repository = "https://github.com/panicbit/recaptcha-rs"
edition = "2018"

[features]

default = ["reqwest/default-tls"]
rustls-tls = ["reqwest/rustls-tls"]

[dependencies]
reqwest = { version = "0.11", features = ["json"], default-features = false }
serde_derive = "1.0.106"
serde = "1.0.106"
failure = "0.1.7"

[dev-dependencies]
serde_json = "1.0.50"
tokio = { version = "1", features = ["macros"] }
